# Changes here will be overwritten by Copier
_commit: v7.3.0-24-g169e035
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-uuid
project_description: Create universally unique identifiers (UUIDs) versions 1, 3,
    4, 5, 6, 7 and 8 in transformations.
project_slug: uuid
project_type: plugin
pypi: true

