# Changes here will be overwritten by Copier
_commit: v6.0.1
_src_path: gh:eccenca/cmem-plugin-template
author_mail: cmempy-developer@eccenca.com
author_name: eccenca GmbH
github_page: https://github.com/eccenca/cmem-plugin-uuid
project_description: Generate UUIDv1, 3, 4, 5, 6, 7 and 8 literals.
project_slug: uuid
pypi: true

