# https://taskfile.dev
---
version: '3'

tasks:

  install:
    desc: Install plugin package in Corporate Memory
    cmds:
      - task build
      - poetry run cmemc admin workspace python install dist/cmem_plugin_uuid*.tar.gz
      - poetry run cmemc admin workspace python list-plugins

  uninstall:
    desc: Unnstall plugin package in Corporate Memory
    cmds:
      - task build
      - poetry run cmemc admin workspace python uninstall cmem-plugin-uuid
      - poetry run cmemc admin workspace python list-plugins
